/*
 * This source file was generated by the Gradle 'init' task
 */
package FL.chaincode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        DUpdate classUnderTest = new DUpdate("sessionID", "modelID", "updateID");
        DUpdateContract contract = new DUpdateContract();
        assertNotNull(classUnderTest.serialize(), "app should have a getsessionID");
        assertNotNull(classUnderTest.getsessionID(), "app should have a getsessionID");
    }
}
